import type { Metadata } from "next";

// These styles apply to every route in the application
import "./globals.css";
import { DrawerProvider } from "./contexts/DrawerProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="jp">
      <body>
        <DrawerProvider>{children}</DrawerProvider>
      </body>
    </html>
  );
}
